### ISSUE TITLE
FR has very few commits

### ISSUE THREAD

**Issue by tofr** [queeniexiang/WaffledOctopie#3]
why
?
?
?

**Comment by fabbbbbiola** [comment]
FR had troubles with opening processing on her home computer but FR works on code with the group during class even though commits are made by other members so there are no merge conflicts. FR has recently resolved the processing issue at home so she will be committing more often.

**Comment by tofr** [comment]
Thrilled to hear. Insight appreciated.



Topher Brown Mykolyk
CS - Stuyvesant HS
+
